package com.jhonfx.portalgun.federation;

import com.jhonfx.portalgun.item.PortalGunItem;
import com.jhonfx.portalgun.network.ModNetwork;
import net.minecraft.core.BlockPos;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.ListTag;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.core.registries.Registries;
import net.minecraft.world.effect.MobEffectInstance;
import net.minecraft.world.effect.MobEffects;
import net.minecraft.world.item.ItemStack;
import net.minecraftforge.event.TickEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;

/**
 * FEDERATION PRISON EVENT
 *
 * Triggered when a player reaches wanted level 5 AND the Federation
 * captures them (handled by FederationThreatHandler via captureTry()).
 *
 * Sequence:
 *  1. Player is incapacitated (slow + blindness + very low health)
 *  2. After 3 s → teleported to prison, items stored in NBT
 *  3. Brainalyzer sequence starts (narrative messages over 30 s)
 *  4. Player escapes by finding portal gun stored in prison locker
 *  5. Portal inhibitor must be disabled (destroy BEDROCK below PRISON_POS)
 *  6. Player can fire portal and leave
 */
public final class FederationPrisonEvent {
    private static final String KEY = "FedPrisonEvent";
    private static final String KEY_ITEMS = "FedConfiscated";
    private static final ResourceKey<net.minecraft.world.level.Level> FED =
            ResourceKey.create(Registries.DIMENSION,
                    new ResourceLocation("portalgun", "federation"));
    /** Visible, survival-breakable portal inhibitor in the prison's central hall. */
    public static final BlockPos INHIBITOR_POS = FederationBuilder.PRISON_POS.above();

    // ── Capture ───────────────────────────────────────────────────────────────
    public static void captureTry(ServerPlayer player) {
        if (player.getPersistentData().getBoolean(KEY)) return; // already captured
        if (FederationThreatHandler.getWanted(player) < 5) return;

        // Incapacitate
        player.addEffect(new MobEffectInstance(MobEffects.BLINDNESS,      60, 0, false, false));
        player.addEffect(new MobEffectInstance(MobEffects.MOVEMENT_SLOWDOWN, 60, 6, false, false));
        player.addEffect(new MobEffectInstance(MobEffects.WEAKNESS,       60, 10, false, false));
        player.setHealth(1.0f);
        player.displayClientMessage(Component.literal(
                "§c[ NOVA FEDERAÇÃO GALÁCTICA ]§r Alvo neutralizado. Iniciando transporte."), false);

        // Mark as being captured; teleport happens in tick
        player.getPersistentData().putBoolean(KEY, true);
        player.getPersistentData().putLong("FedCaptureTime", player.level().getGameTime() + 60);
    }

    // ── Tick handler ──────────────────────────────────────────────────────────
    @SubscribeEvent
    public void onPlayerTick(TickEvent.PlayerTickEvent event) {
        if (event.phase != TickEvent.Phase.END) return;
        if (!(event.player instanceof ServerPlayer player)) return;
        if (player.level().isClientSide()) return;

        CompoundTag data = player.getPersistentData();
        if (!data.getBoolean(KEY)) return;

        long now = player.level().getGameTime();
        long captureTime = data.getLong("FedCaptureTime");

        // Step 1: teleport after 3 s
        if (now >= captureTime && !data.getBoolean("FedInPrison")) {
            transportToPrison(player);
            return;
        }

        if (!data.getBoolean("FedInPrison")) return;

        // Step 2: Brainalyzer narrative (runs for 30 s after arrival)
        long arrivalTime = data.getLong("FedArrivalTime");
        long elapsed     = now - arrivalTime;
        deliverBrainalyzerNarrative(player, elapsed);

        // Step 3: Check escape condition — the visible inhibitor console was destroyed.
        if (player.level().dimension().equals(FED)) {
            boolean inhibitorAlive = player.serverLevel().getBlockState(INHIBITOR_POS)
                    .is(net.minecraft.world.level.block.Blocks.REDSTONE_LAMP);
            if (!inhibitorAlive) {
                releaseFromPrison(player);
            }
        }
    }

    // ── Transport ─────────────────────────────────────────────────────────────
    private static void transportToPrison(ServerPlayer player) {
        ServerLevel fedLevel = player.server.getLevel(FED);
        if (fedLevel == null) return;

        FederationBuilder.ensureBuilt(fedLevel);
        confiscateItems(player);

        // Recreate the accessible console for every capture, including worlds whose
        // Federation complex was generated by an older version of the mod.
        fedLevel.setBlockAndUpdate(INHIBITOR_POS,
                net.minecraft.world.level.block.Blocks.REDSTONE_LAMP.defaultBlockState()
                        .setValue(net.minecraft.world.level.block.RedstoneLampBlock.LIT, true));

        BlockPos cell = FederationBuilder.PRISON_POS.offset(0, 1, -20);
        player.teleportTo(fedLevel, cell.getX() + .5, cell.getY(), cell.getZ() + .5, 0, 0);

        CompoundTag data = player.getPersistentData();
        data.putBoolean("FedInPrison", true);
        data.putLong("FedArrivalTime", player.level().getGameTime());
        data.remove("FedCaptureTime");

        // Activate portal inhibitor
        data.putInt(FederationThreatHandler.KEY_INHIBIT, Integer.MAX_VALUE);

        player.displayClientMessage(Component.literal(
                "§c[ FED PRISON — GROMFLOM SECTOR 7 ]§r\n" +
                "§fSeus itens foram confiscados. Portal Gun removida.\n" +
                "§7Destrua o gerador luminoso no centro da prisão (§fX 55 Y 98 Z 0§7) para recuperar tudo."), false);
    }

    // ── Brainalyzer narrative ─────────────────────────────────────────────────
    private static void deliverBrainalyzerNarrative(ServerPlayer player, long elapsed) {
        // One message per milestone tick (in server ticks, 20/s)
        String msg = switch ((int)(elapsed / 20)) {
            case 5  -> "§b[ BRAINALYZER SÉRIE 9000 ]§r Conectando eletrodos neurais...";
            case 10 -> "§b[ BRAINALYZER ]§r Iniciando varredura de memórias. Relaxe.";
            case 20 -> "§b[ BRAINALYZER ]§r Memória detectada: §ePrimeiro contato com tecnologia interdimensional.";
            case 30 -> "§b[ BRAINALYZER ]§r Memória detectada: §ePortal Gun — origem desconhecida.";
            case 40 -> "§b[ BRAINALYZER ]§r Assinatura neural anômala. Comparando banco de dados...";
            case 50 -> "§b[ BRAINALYZER ]§r §cAVISO: Assinatura Sanchez detectada. Variante não catalogada.";
            case 60 -> "§c[ OFICIAL FEDERAL ]§r §fIsso não é Rick Sanchez padrão. Arquive como SANCHEZ — VARIANTE NÃO IDENTIFICADA.";
            case 70 -> "§b[ BRAINALYZER ]§r Tentando extrair dados completos sobre a variante...";
            case 80 -> "§cSISTEMA SOBRECARREGADO§r — falha na extração. Dados parciais salvos.";
            case 85 -> "§e[ SISTEMA DE SEGURANÇA ]§r Alarme ativado. Contenção iniciada.";
            default -> null;
        };
        if (msg != null && elapsed % 20 == 0) {
            player.displayClientMessage(Component.literal(msg), false);
        }
    }

    // ── Item confiscation ─────────────────────────────────────────────────────
    private static void confiscateItems(ServerPlayer player) {
        ListTag confiscated = new ListTag();
        for (int i = 0; i < player.getInventory().getContainerSize(); i++) {
            ItemStack s = player.getInventory().getItem(i);
            if (s.isEmpty()) continue;
            // Always confiscate portal guns
            if (s.getItem() instanceof PortalGunItem) {
                CompoundTag entry = new CompoundTag();
                entry.putInt("Slot", i);
                s.save(entry);
                confiscated.add(entry);
                player.getInventory().setItem(i, ItemStack.EMPTY);
            }
        }
        player.getPersistentData().put(KEY_ITEMS, confiscated);
    }

    private static void restoreItems(ServerPlayer player) {
        ListTag confiscated = player.getPersistentData().getList(KEY_ITEMS, 10);
        for (int i = 0; i < confiscated.size(); i++) {
            CompoundTag entry = confiscated.getCompound(i);
            ItemStack s = ItemStack.of(entry);
            if (!player.getInventory().add(s)) player.drop(s, false);
        }
        player.getPersistentData().remove(KEY_ITEMS);
    }

    // ── Release ───────────────────────────────────────────────────────────────
    private static void releaseFromPrison(ServerPlayer player) {
        restoreItems(player);
        CompoundTag data = player.getPersistentData();
        data.remove(KEY);
        data.remove("FedInPrison");
        data.remove("FedArrivalTime");
        data.remove(FederationThreatHandler.KEY_INHIBIT);

        // Lower wanted to 3 (still hunted, but can travel)
        FederationThreatHandler.lower(player, 2);

        player.displayClientMessage(Component.literal(
                "§a[ FUGA BEM-SUCEDIDA ]§r Itens recuperados. Portal Gun restaurada.\n" +
                "§7A Federação possui dados incompletos sobre §cSANCHEZ — VARIANTE NÃO IDENTIFICADA.§r"), false);
    }
}
