package com.jhonfx.portalgun.citadel;

import com.jhonfx.portalgun.entity.CitadelNpcEntity;
import com.jhonfx.portalgun.init.ModBlocks;
import com.jhonfx.portalgun.init.ModEntityTypes;
import net.minecraft.core.BlockPos;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.decoration.ArmorStand;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.phys.AABB;

public final class CitadelBuilder {
    private static final int CURRENT_LAYOUT_VERSION = 8;
    public static final BlockPos CENTER = new BlockPos(0, 96, 0);
    public static final BlockPos ARRIVAL = new BlockPos(0, 98, 10);
    public static final BlockPos REFUGE = new BlockPos(0, 98, 112);

    public static void ensureBuilt(ServerLevel level) {
        if (com.jhonfx.portalgun.curve.CurveSavedData.get(level).broken()) {
            if (com.jhonfx.portalgun.curve.CurveSavedData.get(level).collapseTicks() == 0) ensureRefuge(level);
            return; // A return trip must never repair the destroyed Curve or repopulate the city.
        }
        CitadelSavedData data = CitadelSavedData.get(level);
        if (data.getLayoutVersion() < CURRENT_LAYOUT_VERSION) {
            CitadelV4Layout.request(level);
            return;
        }
        if (!data.isBuilt()) {
            build(level);
            data.markBuilt();
        }
        ensureExpansion(level);
        decorateCurveWing(level);
        ensurePersonnel(level);
        ensureDistrictPopulation(level);
        // Garantia: CURVE_CORE e DIMENSIONAL_DRIVE sempre presentes na Curva Finita Central.
        // O rebuildCombatCitadel pode sobrescrever esses blocos com publicPlaza — restauramos aqui.
        ensureCurveWingMachinery(level);
        ensureNavigation(level);
    }

    static void finishV4(ServerLevel level) {
        CitadelSavedData data=CitadelSavedData.get(level);
        data.markBuilt();
        data.setLayoutVersion(CURRENT_LAYOUT_VERSION);
        ensureExpansion(level);
        ensureCurveWingMachinery(level);
        decorateCurveWing(level);
        ensurePersonnel(level);
        ensureNavigation(level);
        buildV7Interiors(level);
    }

    /** Opens real walkable corridors through dome rims, tower bulkheads and transit tubes. */
    private static void ensureNavigation(ServerLevel level){
        CitadelSavedData data=CitadelSavedData.get(level);if(data.getNavigationVersion()>=6)return;
        BlockPos hub=new BlockPos(0,96,0);
        carveRoute(level,hub,new BlockPos(-82,96,12),3);
        carveRoute(level,hub,new BlockPos(86,96,8),3);
        carveRoute(level,hub,new BlockPos(-18,96,-82),3);
        carveRoute(level,hub,new BlockPos(0,96,-76),3);
        // Wide, unobstructed concourses around every satellite terminal. This
        // also repairs worlds where an older tower shell covered the bridge exit.
        for(BlockPos district:new BlockPos[]{new BlockPos(-82,96,12),new BlockPos(86,96,8),new BlockPos(-18,96,-82)}){
            for(int x=-8;x<=8;x++)for(int z=-8;z<=8;z++)if(x*x+z*z<=64){
                level.setBlock(district.offset(x,0,z),(Math.abs(x)+Math.abs(z))%7==0?Blocks.SEA_LANTERN.defaultBlockState():ModBlocks.CITADEL_ALLOY.get().defaultBlockState(),2);
                for(int y=1;y<=5;y++)level.setBlock(district.offset(x,y,z),Blocks.AIR.defaultBlockState(),2);
            }
        }
        // Arrival and service plaza remain completely open at player height.
        for(int x=-18;x<=18;x++)for(int z=-16;z<=18;z++)for(int y=97;y<=101;y++){
            if(x*x+z*z<=19*19)level.setBlock(new BlockPos(x,y,z),Blocks.AIR.defaultBlockState(),2);
        }
        // Reinstall the five terminals after opening the plaza; older layouts
        // placed them directly in the volume that had to be cleared.
        set(level,CENTER.offset(12,1,4),ModBlocks.CITADEL_SHOP.get().defaultBlockState());
        set(level,CENTER.offset(-12,1,4),ModBlocks.CITADEL_WORKSHOP.get().defaultBlockState());
        set(level,CENTER.offset(0,1,12),ModBlocks.CITADEL_MISSION_TERMINAL.get().defaultBlockState());
        set(level,CENTER.offset(-8,1,-12),ModBlocks.NEURAL_SCANNER.get().defaultBlockState());
        set(level,CENTER.offset(8,1,-12),ModBlocks.COUNCIL_ARCHIVE.get().defaultBlockState());
        // Final v8 cross-concourse removes the last central bottlenecks.
        carveRoute(level,new BlockPos(-88,96,0),new BlockPos(92,96,0),5);
        carveRoute(level,new BlockPos(0,96,-88),new BlockPos(0,96,75),5);
        // Internal maintenance ladders make every tower level reachable without
        // breaking the solid nine-block separator decks generated by the dome.
        towerLadder(level,0,0,9,44);
        towerLadder(level,-82,12,5,22);
        towerLadder(level,86,8,6,27);
        towerLadder(level,-18,-82,6,30);
        // The cross-concourse above cuts through the contract terminal at z=12.
        // Restore services after ALL carving, not before it.
        set(level,CENTER.offset(12,1,4),ModBlocks.CITADEL_SHOP.get().defaultBlockState());
        set(level,CENTER.offset(-12,1,4),ModBlocks.CITADEL_WORKSHOP.get().defaultBlockState());
        set(level,CENTER.offset(0,1,12),ModBlocks.CITADEL_MISSION_TERMINAL.get().defaultBlockState());
        set(level,CENTER.offset(-8,1,-12),ModBlocks.NEURAL_SCANNER.get().defaultBlockState());
        set(level,CENTER.offset(8,1,-12),ModBlocks.COUNCIL_ARCHIVE.get().defaultBlockState());
        data.setNavigationVersion(6);
    }

    private static void towerLadder(ServerLevel level,int cx,int cz,int radius,int height){
        int x=cx+Math.max(1,radius-2),supportX=x+1,top=96+height-1;
        for(int y=97;y<=top;y++){
            BlockPos support=new BlockPos(supportX,y,cz),ladder=new BlockPos(x,y,cz);
            level.setBlock(support,(y%8==0?Blocks.SEA_LANTERN:ModBlocks.CITADEL_ALLOY.get()).defaultBlockState(),2);
            level.setBlock(ladder,Blocks.LADDER.defaultBlockState().setValue(
                    net.minecraft.world.level.block.LadderBlock.FACING,net.minecraft.core.Direction.WEST),2);
            level.setBlock(ladder.relative(net.minecraft.core.Direction.WEST),Blocks.AIR.defaultBlockState(),2);
        }
        for(int dx=-1;dx<=1;dx++)for(int dz=-1;dz<=1;dz++)for(int y=top;y<=top+2;y++)
            if(!(dx==1&&dz==0))level.setBlock(new BlockPos(x+dx,y,cz+dz),Blocks.AIR.defaultBlockState(),2);
    }

    private static void carveRoute(ServerLevel level,BlockPos from,BlockPos to,int halfWidth){
        int dx=to.getX()-from.getX(),dz=to.getZ()-from.getZ(),steps=Math.max(Math.abs(dx),Math.abs(dz));boolean eastWest=Math.abs(dx)>=Math.abs(dz);
        for(int i=0;i<=steps;i++){double t=i/(double)Math.max(1,steps);int cx=(int)Math.round(from.getX()+dx*t),cz=(int)Math.round(from.getZ()+dz*t);
            for(int w=-halfWidth;w<=halfWidth;w++){int x=cx+(eastWest?0:w),z=cz+(eastWest?w:0);BlockPos floor=new BlockPos(x,96,z);level.setBlock(floor,i%9==0&&w==0?Blocks.SEA_LANTERN.defaultBlockState():ModBlocks.CITADEL_ALLOY.get().defaultBlockState(),2);for(int y=97;y<=101;y++)level.setBlock(new BlockPos(x,y,z),Blocks.AIR.defaultBlockState(),2);}
        }
    }

    public static void ensureRefuge(ServerLevel level) {
        CitadelSavedData data = CitadelSavedData.get(level);
        if (data.getRefugeVersion() >= 3) return;
        // v2 tinha apenas seis pares. Remova somente os sobreviventes do
        // abrigo antes de recriar o elenco, evitando duplicatas em mundos
        // atualizados sem tocar em NPCs que o jogador levou para outro lugar.
        level.getEntitiesOfClass(CitadelNpcEntity.class, new AABB(REFUGE).inflate(28),
                npc -> npc.hasCustomName() && npc.getCustomName().getString().contains("Sobrevivente"))
                .forEach(net.minecraft.world.entity.Entity::discard);
        for (int x = -24; x <= 24; x++) for (int z = -18; z <= 18; z++) {
            set(level, REFUGE.offset(x, -1, z), (x % 5 == 0 && z % 5 == 0)
                    ? Blocks.SEA_LANTERN.defaultBlockState() : ModBlocks.CITADEL_ALLOY.get().defaultBlockState());
            if (Math.abs(x) == 24 || Math.abs(z) == 18)
                set(level, REFUGE.offset(x, 0, z), ModBlocks.CITADEL_GLASS.get().defaultBlockState());
        }
        booth(level, REFUGE.offset(-14, 0, 7), ModBlocks.CITADEL_WORKSHOP.get().defaultBlockState(), ModBlocks.CITADEL_CIRCUIT.get().defaultBlockState());
        booth(level, REFUGE.offset(14, 0, 7), ModBlocks.CITADEL_SHOP.get().defaultBlockState(), ModBlocks.CITADEL_GOLD.get().defaultBlockState());
        booth(level, REFUGE.offset(0, 0, 10), ModBlocks.CITADEL_MISSION_TERMINAL.get().defaultBlockState(), ModBlocks.CITADEL_CIRCUIT.get().defaultBlockState());
        String[] ricks={"Rick D-151","Rick B-921","Rick J-19ζ7","Rick C-500A","Rick K-22","Rick R-426","Rick T-808","Rick Z-144","Rick N-731","Rick Q-009"};
        String[] mortys={"Morty D-151","Morty B-921","Morty J-19ζ7","Morty C-500A","Morty K-22","Morty R-426","Morty T-808","Morty Z-144","Morty N-731","Morty Q-009"};
        for(int i=0;i<10;i++){
            int row=i/5,col=i%5;
            spawnPersonnel(level,CitadelNpcEntity.Variant.RICK,REFUGE.offset(-10+col*5,0,-7+row*3),ricks[i]+" — Sobrevivente");
            spawnPersonnel(level,i%2==0?CitadelNpcEntity.Variant.MORTY_WORKER:CitadelNpcEntity.Variant.MORTY_REBEL,
                    REFUGE.offset(-10+col*5,0,2+row*3),mortys[i]+" — Sobrevivente");
        }
        data.setRefugeVersion(3);
    }

    private static void build(ServerLevel level) {
        BlockState panel = ModBlocks.CITADEL_PANEL.get().defaultBlockState();
        BlockState gold = ModBlocks.CITADEL_GOLD.get().defaultBlockState();
        BlockState circuit = ModBlocks.CITADEL_CIRCUIT.get().defaultBlockState();
        BlockState glass = ModBlocks.CITADEL_GLASS.get().defaultBlockState();
        BlockState alloy = ModBlocks.CITADEL_ALLOY.get().defaultBlockState();

        disk(level, CENTER, 47, panel, alloy);
        dome(level, CENTER.above(), 47, 29, glass, alloy);

        BlockPos east = CENTER.offset(62, 0, 16);
        BlockPos west = CENTER.offset(-62, 0, 16);
        BlockPos south = CENTER.offset(0, 0, 67);
        for (BlockPos district : new BlockPos[]{east, west, south}) {
            disk(level, district, 25, panel, alloy);
            dome(level, district.above(), 25, 18, glass, alloy);
            bridge(level, CENTER, district, 5, panel, circuit);
        }

        // Central transit plaza and portal beacon.
        disk(level, CENTER.above(), 10, Blocks.SMOOTH_QUARTZ.defaultBlockState(), circuit);
        for (int y = 1; y <= 8; y++) set(level, CENTER.above(y), y % 2 == 0 ? circuit : glass);
        ring(level, CENTER.above(10), 7, gold);
        ring(level, CENTER.above(13), 5, circuit);

        // Council tower, commerce, workshop and habitation spires.
        tower(level, CENTER.offset(0, 1, -27), 8, 31, gold, glass);
        tower(level, CENTER.offset(23, 1, -13), 6, 22, alloy, circuit);
        tower(level, CENTER.offset(-23, 1, -13), 6, 25, panel, glass);
        tower(level, east.above(), 8, 24, panel, glass);
        tower(level, west.above(), 8, 24, gold, glass);
        tower(level, south.above(), 9, 28, alloy, circuit);

        // Service counters are deliberately visible from the arrival plaza.
        booth(level, CENTER.offset(15, 1, 9), ModBlocks.CITADEL_SHOP.get().defaultBlockState(), gold);
        booth(level, CENTER.offset(-15, 1, 9), ModBlocks.CITADEL_WORKSHOP.get().defaultBlockState(), circuit);
        booth(level, CENTER.offset(15, 1, -9), ModBlocks.CITADEL_MISSION_TERMINAL.get().defaultBlockState(), circuit);
        booth(level, CENTER.offset(-15, 1, -9), ModBlocks.NEURAL_SCANNER.get().defaultBlockState(), gold);

        // Layered roads make the interior feel like a vertical, inhabited city.
        elevatedRing(level, CENTER, 18, 6, alloy, circuit);
        elevatedRing(level, CENTER, 31, 13, panel, gold);
        spawnCitizens(level);
        spawnC524(level);
    }

    private static void ensureExpansion(ServerLevel level) {
        CitadelSavedData data=CitadelSavedData.get(level);
        if(data.isCurveWingBuilt()){spawnC524(level);return;}
        booth(level,CENTER.offset(15,1,-9),ModBlocks.CITADEL_MISSION_TERMINAL.get().defaultBlockState(),ModBlocks.CITADEL_CIRCUIT.get().defaultBlockState());
        booth(level,CENTER.offset(-15,1,-9),ModBlocks.NEURAL_SCANNER.get().defaultBlockState(),ModBlocks.CITADEL_GOLD.get().defaultBlockState());
        buildCurveWing(level);
        spawnC524(level);
        data.markCurveWingBuilt();
    }

    /**
     * Garante que o CURVE_CORE e o DIMENSIONAL_DRIVE estão presentes na estrutura
     * da Curva Finita Central. É chamado após qualquer rebuild para que o
     * publicPlaza não apague esses blocos críticos.
     */
    private static void ensureCurveWingMachinery(ServerLevel level) {
        BlockPos wing = CENTER.offset(0, 0, -76);
        // CURVE_CORE: centro da plataforma, y+2 do disco base
        BlockPos corePos = wing.above(2);
        if (!(level.getBlockState(corePos).getBlock() instanceof com.jhonfx.portalgun.block.CitadelServiceBlock)) {
            set(level, corePos, ModBlocks.CURVE_CORE.get().defaultBlockState());
        }
        // DIMENSIONAL_DRIVE: 7 blocos à esquerda do centro, mesma altura
        BlockPos drivePos = wing.offset(-7, 2, 0);
        if (!level.getBlockState(drivePos).is(ModBlocks.DIMENSIONAL_DRIVE.get())) {
            set(level, drivePos, ModBlocks.DIMENSIONAL_DRIVE.get().defaultBlockState());
        }
    }

    private static void buildCurveWing(ServerLevel level){
        BlockPos wing=CENTER.offset(0,0,-76);
        BlockState alloy=ModBlocks.CITADEL_ALLOY.get().defaultBlockState(),gold=ModBlocks.CITADEL_GOLD.get().defaultBlockState();
        BlockState glass=ModBlocks.CITADEL_GLASS.get().defaultBlockState(),circuit=ModBlocks.CITADEL_CIRCUIT.get().defaultBlockState();
        disk(level,wing,22,alloy,gold);dome(level,wing.above(),22,17,glass,gold);bridge(level,CENTER,wing,4,alloy,circuit);
        // Secured research floor, archive vaults and elevated observation platform.
        for(int x=-13;x<=13;x++)for(int z=-13;z<=13;z++)if(Math.abs(x)==13||Math.abs(z)==13)set(level,wing.offset(x,1,z),gold);
        for(int y=2;y<=6;y++)for(int x=-13;x<=13;x++)for(int z:new int[]{-13,13})set(level,wing.offset(x,y,z),y%3==0?glass:alloy);
        for(int y=2;y<=6;y++)for(int z=-13;z<=13;z++)for(int x:new int[]{-13,13})set(level,wing.offset(x,y,z),y%3==0?glass:alloy);
        set(level,wing.above(2),ModBlocks.CURVE_CORE.get().defaultBlockState());
        set(level,wing.offset(-7,2,0),ModBlocks.DIMENSIONAL_DRIVE.get().defaultBlockState());
        for(int z=-8;z<=8;z+=4){set(level,wing.offset(8,2,z),ModBlocks.COUNCIL_ARCHIVE.get().defaultBlockState());set(level,wing.offset(9,2,z),ModBlocks.COUNCIL_ARCHIVE.get().defaultBlockState());}
        elevatedRing(level,wing,10,8,alloy,circuit);ring(level,wing.above(11),7,gold);ring(level,wing.above(14),5,circuit);
    }

    /**
     * The Curve is made from persistent entities instead of a particle cloud.
     * That keeps its shape visible from every angle and avoids respawning
     * hundreds of particles every tick.
     */
    private static void decorateCurveWing(ServerLevel level) {
        BlockPos wing=CENTER.offset(0,0,-76);
        boolean exists=!level.getEntitiesOfClass(com.jhonfx.portalgun.entity.CurveNodeEntity.class,
                new AABB(wing).inflate(18), n -> true).isEmpty();
        if(!exists) {
            // Build ring-by-ring, keeping a reference to the previous node in each
            // ring so we can link() them into a connected lattice (tether particles).
            com.jhonfx.portalgun.entity.CurveNodeEntity firstInRing = null;
            com.jhonfx.portalgun.entity.CurveNodeEntity previous = null;
            for(int ring=0;ring<4;ring++) {
                int nodes=10+ring*4;
                double radius=2.4+ring*1.45;
                firstInRing = null;
                previous = null;
                for(int i=0;i<nodes;i++) {
                    double angle=i*Math.PI*2.0/nodes+ring*.53;
                    double y=4.1+(ring-1.5)*1.15+Math.sin(angle*3.0)*.72;
                    com.jhonfx.portalgun.entity.CurveNodeEntity node =
                            com.jhonfx.portalgun.init.ModEntityTypes.CURVE_NODE.get().create(level);
                    if(node==null)continue;
                    node.setRing(ring);
                    node.setBase(wing.getX()+.5+Math.cos(angle)*radius, wing.getY()+y,
                            wing.getZ()+.5+Math.sin(angle)*radius);
                    node.setYRot((float)Math.toDegrees(-angle));
                    level.addFreshEntity(node);

                    if (firstInRing == null) firstInRing = node;
                    if (previous != null) previous.linkTo(node);
                    previous = node;
                }
                // Close the ring loop
                if (previous != null && firstInRing != null) previous.linkTo(firstInRing);
            }
        }
        createGuide(level,wing.offset(0,3,16),"CURVA FINITA CENTRAL  ↓");
        createGuide(level,CENTER.offset(0,4,-38),"CURVA FINITA CENTRAL  →");
    }

    private static void createGuide(ServerLevel level,BlockPos pos,String label) {
        boolean exists=!level.getEntitiesOfClass(ArmorStand.class,new AABB(pos).inflate(2),
                stand -> stand.getPersistentData().getBoolean("PortalGunCurveGuide")).isEmpty();
        if(exists)return;
        ArmorStand guide=EntityType.ARMOR_STAND.create(level); if(guide==null)return;
        guide.moveTo(pos.getX()+.5,pos.getY(),pos.getZ()+.5,0,0);
        guide.setInvisible(true); guide.setInvulnerable(true); guide.setNoGravity(true); configureStand(guide,false);
        guide.setCustomName(net.minecraft.network.chat.Component.literal(label)); guide.setCustomNameVisible(true);
        guide.getPersistentData().putBoolean("PortalGunCurveGuide",true);
        level.addFreshEntity(guide);
    }

    private static void configureStand(ArmorStand stand,boolean small) {
        net.minecraft.nbt.CompoundTag tag=new net.minecraft.nbt.CompoundTag();
        stand.saveWithoutId(tag);tag.putBoolean("Marker",true);tag.putBoolean("Small",small);
        tag.putBoolean("Invisible",true);tag.putBoolean("Invulnerable",true);tag.putBoolean("NoGravity",true);
        stand.load(tag);
    }

    /**
     * 0.9 combat layout. It deliberately replaces only public streets and empty
     * air above them, preserving player interiors while fixing the old vertical
     * rings that had no climbable route.
     */
    private static void rebuildCombatCitadel(ServerLevel level) {
        BlockState panel=ModBlocks.CITADEL_PANEL.get().defaultBlockState();
        BlockState alloy=ModBlocks.CITADEL_ALLOY.get().defaultBlockState();
        BlockState gold=ModBlocks.CITADEL_GOLD.get().defaultBlockState();
        BlockState circuit=ModBlocks.CITADEL_CIRCUIT.get().defaultBlockState();
        BlockState glass=ModBlocks.CITADEL_GLASS.get().defaultBlockState();

        // A broad, readable ground plan: arrival plaza, four districts and an
        // unobstructed central avenue. Embedded light prevents hostile spawns.
        publicPlaza(level,CENTER.above(),34,panel,alloy,circuit);
        avenue(level,CENTER.offset(0,1,-76),CENTER.offset(0,1,69),7,panel,circuit);
        avenue(level,CENTER.offset(-64,1,16),CENTER.offset(64,1,16),6,alloy,circuit);
        publicPlaza(level,CENTER.offset(62,1,16),19,panel,gold,circuit);
        publicPlaza(level,CENTER.offset(-62,1,16),19,alloy,gold,circuit);
        publicPlaza(level,CENTER.offset(0,1,67),20,panel,alloy,circuit);
        publicPlaza(level,CENTER.offset(0,1,-76),17,alloy,gold,circuit);

        // Two spacious skyline decks. Each has four real ramps: one block of
        // height per three blocks of travel, so every floor is walkable.
        skyDeck(level,CENTER,24,8,alloy,gold,circuit);
        skyDeck(level,CENTER,38,15,panel,alloy,circuit);
        for(net.minecraft.core.Direction d:net.minecraft.core.Direction.Plane.HORIZONTAL) {
            accessibleRamp(level,CENTER,d,24,8,5,panel,circuit);
            accessibleRamp(level,CENTER,d,38,15,5,alloy,circuit);
        }

        // Council chamber and combat-training platform give the city a clear
        // silhouette without sealing the paths under decorative geometry.
        openCouncil(level,CENTER.offset(0,1,-31),gold,glass,circuit);
        trainingArena(level,CENTER.offset(0,1,35),alloy,gold,circuit);
        lightPublicSpace(level,CENTER,82);
    }

    private static void publicPlaza(ServerLevel level,BlockPos center,int radius,BlockState floor,BlockState rim,BlockState light){
        for(int x=-radius;x<=radius;x++)for(int z=-radius;z<=radius;z++){
            int d=x*x+z*z;if(d>radius*radius)continue;
            BlockPos p=center.offset(x,0,z);
            set(level,p,d>(radius-2)*(radius-2)?rim:((x*x+z*z)%37==0?light:floor));
            if((x+z)%9==0)set(level,p.below(),Blocks.SEA_LANTERN.defaultBlockState());
            for(int y=1;y<=3;y++)if(level.getBlockState(p.above(y)).isAir())set(level,p.above(y),Blocks.AIR.defaultBlockState());
        }
    }

    private static void avenue(ServerLevel level,BlockPos from,BlockPos to,int width,BlockState floor,BlockState light){
        int dx=to.getX()-from.getX(),dz=to.getZ()-from.getZ(),steps=Math.max(Math.abs(dx),Math.abs(dz));
        for(int i=0;i<=steps;i++){
            double t=i/(double)steps;int x=(int)Math.round(from.getX()+dx*t),z=(int)Math.round(from.getZ()+dz*t);
            boolean eastWest=Math.abs(dx)>=Math.abs(dz);
            for(int w=-width;w<=width;w++){
                BlockPos p=new BlockPos(x+(eastWest?0:w),from.getY(),z+(eastWest?w:0));
                set(level,p,(i%8==0&&Math.abs(w)==width-1)?light:floor);
                for(int y=1;y<=4;y++)set(level,p.above(y),Blocks.AIR.defaultBlockState());
            }
        }
    }

    private static void skyDeck(ServerLevel level,BlockPos center,int radius,int height,BlockState floor,BlockState rim,BlockState light){
        for(int i=0;i<360;i+=2){
            double a=Math.toRadians(i);
            for(int w=-3;w<=3;w++){
                int x=(int)Math.round(Math.cos(a)*(radius+w));int z=(int)Math.round(Math.sin(a)*(radius+w));
                BlockPos p=center.offset(x,height,z);set(level,p,Math.abs(w)==3?rim:(i%24==0?light:floor));
                set(level,p.below(),i%12==0?Blocks.SEA_LANTERN.defaultBlockState():floor);
                for(int y=1;y<=3;y++)set(level,p.above(y),Blocks.AIR.defaultBlockState());
            }
        }
    }

    private static void accessibleRamp(ServerLevel level,BlockPos center,net.minecraft.core.Direction direction,int radius,int height,int width,BlockState floor,BlockState light){
        int length=height*3;
        for(int step=0;step<=length;step++){
            int y=Math.min(height,step/3);int distance=radius-length+step;
            BlockPos middle=center.relative(direction,distance).above(y);
            net.minecraft.core.Direction side=direction.getClockWise();
            for(int w=-width;w<=width;w++){
                BlockPos p=middle.relative(side,w);set(level,p,(step%9==0&&Math.abs(w)==width)?light:floor);
                for(int clear=1;clear<=3;clear++)set(level,p.above(clear),Blocks.AIR.defaultBlockState());
            }
        }
    }

    /** Interior pass for layout v7: readable districts and reachable vertical streets. */
    private static void buildV7Interiors(ServerLevel level){
        BlockState panel=ModBlocks.CITADEL_PANEL.get().defaultBlockState(),alloy=ModBlocks.CITADEL_ALLOY.get().defaultBlockState();
        BlockState gold=ModBlocks.CITADEL_GOLD.get().defaultBlockState(),circuit=ModBlocks.CITADEL_CIRCUIT.get().defaultBlockState();
        // Two open skyline streets. Every deck receives four shallow ramps.
        skyDeck(level,CENTER,20,7,alloy,gold,circuit);
        skyDeck(level,CENTER,33,13,panel,alloy,circuit);
        for(net.minecraft.core.Direction direction:net.minecraft.core.Direction.Plane.HORIZONTAL){
            accessibleRamp(level,CENTER,direction,20,7,3,panel,circuit);
            accessibleRamp(level,CENTER,direction,33,13,3,alloy,circuit);
        }
        BlockPos commerce=CENTER.offset(-82,1,12),academy=CENTER.offset(86,1,8),curve=CENTER.offset(-18,1,-82);
        publicPlaza(level,commerce,14,alloy,gold,circuit);
        publicPlaza(level,academy,14,panel,alloy,circuit);
        publicPlaza(level,curve,13,alloy,gold,circuit);
        booth(level,commerce.offset(-10,0,0),ModBlocks.CITADEL_SHOP.get().defaultBlockState(),gold);
        booth(level,commerce.offset(10,0,0),ModBlocks.CITADEL_WORKSHOP.get().defaultBlockState(),circuit);
        booth(level,academy.offset(-10,0,0),ModBlocks.CITADEL_MISSION_TERMINAL.get().defaultBlockState(),circuit);
        booth(level,academy.offset(10,0,0),ModBlocks.NEURAL_SCANNER.get().defaultBlockState(),gold);
        trainingArena(level,academy.offset(0,0,-1),panel,gold,circuit);
        createGuide(level,commerce.above(4),"DISTRITO COMERCIAL");
        createGuide(level,academy.above(4),"ACADEMIA E CONTRATOS");
        createGuide(level,curve.above(4),"CURVA FINITA CENTRAL");
        lightPublicSpace(level,CENTER,88);
        ensureDistrictPopulation(level);
    }

    private static void ensureDistrictPopulation(ServerLevel level){
        java.util.List<CitadelNpcEntity> citizens=level.getEntitiesOfClass(CitadelNpcEntity.class,new AABB(CENTER).inflate(115),
                npc->npc.getVariant()!=CitadelNpcEntity.Variant.GUARD&&npc.getVariant()!=CitadelNpcEntity.Variant.COUNCIL);
        if(citizens.size()>=30)return;
        BlockPos[] spots={CENTER.offset(-82,2,12),CENTER.offset(-75,2,17),CENTER.offset(-88,2,6),CENTER.offset(86,2,8),CENTER.offset(78,2,13),CENTER.offset(92,2,2),CENTER.offset(-18,2,-82),CENTER.offset(-10,2,-78),CENTER.offset(-25,2,-88),CENTER.offset(0,2,67)};
        String[] names={"Rick M-302","Morty M-302","Rick Xenon-7","Rick L-808","Morty L-808","Rick Omega-51","Morty Operário 19","Rick Arquivista V-4","Morty Rebelde K-9","Rick do Trânsito C-12"};
        int needed=30-citizens.size();
        for(int i=0;i<spots.length&&i<needed;i++)spawnPersonnel(level,i%3==1?CitadelNpcEntity.Variant.MORTY_WORKER:i%3==2?CitadelNpcEntity.Variant.MORTY_REBEL:CitadelNpcEntity.Variant.RICK,spots[i],names[i]);
    }

    private static void openCouncil(ServerLevel level,BlockPos center,BlockState frame,BlockState glass,BlockState light){
        // Domed outer shell
        publicPlaza(level,center,11,Blocks.SMOOTH_QUARTZ.defaultBlockState(),frame,light);
        for(int y=1;y<=16;y++)for(int i=0;i<360;i+=12){
            double a=Math.toRadians(i);int r=11-y/4;
            if(r<5)r=5;BlockPos p=center.offset((int)Math.round(Math.cos(a)*r),y,(int)Math.round(Math.sin(a)*r));
            set(level,p,(i%48==0)?frame:glass);
        }
        ring(level,center.above(17),6,light);

        // ── Central holoscreen pillar (displays Council business) ────────────
        for (int y = 1; y <= 6; y++) set(level, center.above(y), ModBlocks.OMEGA_ENERGY_GLASS.get().defaultBlockState());
        set(level, center.above(7), light);

        // ── Round table (raised ring platform around the pillar) ──────────────
        for (int x = -4; x <= 4; x++) for (int z = -4; z <= 4; z++) {
            double d = Math.sqrt(x*x + z*z);
            if (d >= 2.2 && d <= 4.0) {
                set(level, center.offset(x, 1, z), Blocks.SMOOTH_QUARTZ.defaultBlockState());
                if ((x + z & 3) == 0) set(level, center.offset(x, 1, z), light);
            }
        }

        // ── 5 Council seats around the table, evenly spaced ────────────────────
        for (int i = 0; i < 5; i++) {
            double a = i * Math.PI * 2 / 5.0;
            int sx = (int) Math.round(Math.cos(a) * 6.0);
            int sz = (int) Math.round(Math.sin(a) * 6.0);
            BlockPos seatPos = center.offset(sx, 1, sz);
            // Seat platform + backrest
            set(level, seatPos, frame);
            set(level, seatPos.above(), Blocks.PURPLE_STAINED_GLASS.defaultBlockState());
            // Podium light
            set(level, seatPos.relative(net.minecraft.core.Direction.UP, 2), light);
        }

        // ── Entrance path marker ─────────────────────────────────────────────
        for (int z = 9; z <= 11; z++) set(level, center.offset(0, 1, z), frame);
    }

    private static void trainingArena(ServerLevel level,BlockPos center,BlockState floor,BlockState rim,BlockState light){
        publicPlaza(level,center,13,floor,rim,light);
        for(int i=0;i<360;i+=45){double a=Math.toRadians(i);BlockPos p=center.offset((int)Math.round(Math.cos(a)*11),1,(int)Math.round(Math.sin(a)*11));for(int y=0;y<5;y++)set(level,p.above(y),y==4?light:rim);}
    }

    private static void lightPublicSpace(ServerLevel level,BlockPos center,int radius){
        for(int x=-radius;x<=radius;x+=8)for(int z=-radius;z<=radius;z+=8){
            if(x*x+z*z>radius*radius)continue;BlockPos floor=center.offset(x,1,z);
            if(!level.getBlockState(floor).isAir())set(level,floor,Blocks.SEA_LANTERN.defaultBlockState());
        }
    }

    private static void spawnC524(ServerLevel level) {
        boolean exists=!level.getEntitiesOfClass(CitadelNpcEntity.class,new net.minecraft.world.phys.AABB(CENTER).inflate(80),
                npc -> npc.getVariant()==CitadelNpcEntity.Variant.C524).isEmpty();
        if(exists)return;
        CitadelNpcEntity npc=ModEntityTypes.CITADEL_CITIZEN.get().create(level); if(npc==null)return;
        npc.moveTo(CENTER.getX()-12.5,CENTER.getY()+2,CENTER.getZ()-22.5,0,0);
        npc.setVariant(CitadelNpcEntity.Variant.C524); npc.setCustomName(net.minecraft.network.chat.Component.literal("Rick C-524"));
        npc.setCustomNameVisible(true); npc.setPersistenceRequired(); level.addFreshEntity(npc);
    }

    private static void disk(ServerLevel level, BlockPos center, int radius, BlockState floor, BlockState rim) {
        for (int x=-radius;x<=radius;x++) for (int z=-radius;z<=radius;z++) {
            int d2=x*x+z*z;
            if (d2>radius*radius) continue;
            BlockState state=d2>(radius-2)*(radius-2)?rim:((x+z)%11==0?ModBlocks.CITADEL_CIRCUIT.get().defaultBlockState():floor);
            set(level,center.offset(x,0,z),state);
            set(level,center.offset(x,-1,z),Blocks.REINFORCED_DEEPSLATE.defaultBlockState());
        }
    }

    private static void dome(ServerLevel level, BlockPos center, int radius, int height,
                             BlockState glass, BlockState rib) {
        for (int y=0;y<=height;y++) {
            double ringRadius=radius*Math.sqrt(Math.max(0.0,1.0-(y/(double)height)*(y/(double)height)));
            int bound=(int)Math.ceil(ringRadius)+1;
            for(int x=-bound;x<=bound;x++) for(int z=-bound;z<=bound;z++) {
                double d=Math.sqrt(x*x+z*z);
                if(Math.abs(d-ringRadius)>0.62) continue;
                boolean support=(Math.abs(x)<=1||Math.abs(z)<=1||y%8==0);
                set(level,center.offset(x,y,z),support?rib:glass);
            }
        }
    }

    private static void bridge(ServerLevel level, BlockPos from, BlockPos to, int width,
                               BlockState floor, BlockState light) {
        int dx=to.getX()-from.getX(), dz=to.getZ()-from.getZ();
        int steps=Math.max(Math.abs(dx),Math.abs(dz));
        for(int i=0;i<=steps;i++) {
            double t=i/(double)steps;
            int x=(int)Math.round(from.getX()+dx*t), z=(int)Math.round(from.getZ()+dz*t);
            boolean eastWest=Math.abs(dx)>=Math.abs(dz);
            for(int w=-width;w<=width;w++) {
                BlockPos p=new BlockPos(x+(eastWest?0:w),from.getY()+1,z+(eastWest?w:0));
                set(level,p,(i%7==0&&w==0)?light:floor);
            }
        }
    }

    private static void tower(ServerLevel level, BlockPos base, int radius, int height,
                              BlockState wall, BlockState window) {
        for(int y=0;y<=height;y++) {
            int r=Math.max(3,radius-y/10);
            for(int x=-r;x<=r;x++) for(int z=-r;z<=r;z++) {
                double d=Math.sqrt(x*x+z*z);
                if(y==0||y==height) {
                    if(d<=r) set(level,base.offset(x,y,z),wall);
                } else if(d>=r-0.8&&d<=r+0.2) {
                    boolean lit=(y%5==2)&&(Math.abs(x)<=1||Math.abs(z)<=1);
                    set(level,base.offset(x,y,z),lit?window:wall);
                }
            }
        }
    }

    private static void booth(ServerLevel level, BlockPos center, BlockState service, BlockState trim) {
        for(int x=-3;x<=3;x++) for(int z=-2;z<=2;z++) set(level,center.offset(x,0,z),trim);
        for(int x=-3;x<=3;x++) set(level,center.offset(x,4,-2),trim);
        for(int y=1;y<=4;y++) for(int x : new int[]{-3,3}) set(level,center.offset(x,y,-2),trim);
        set(level,center.offset(0,1,-1),service);
        set(level,center.offset(0,2,-2),ModBlocks.CITADEL_CIRCUIT.get().defaultBlockState());
    }

    private static void elevatedRing(ServerLevel level, BlockPos center, int radius, int y,
                                     BlockState floor, BlockState light) {
        for(int i=0;i<360;i+=2) {
            double a=Math.toRadians(i);
            int x=(int)Math.round(Math.cos(a)*radius),z=(int)Math.round(Math.sin(a)*radius);
            for(int w=-2;w<=2;w++) {
                int ix=(int)Math.round(Math.cos(a)*(radius+w)),iz=(int)Math.round(Math.sin(a)*(radius+w));
                set(level,center.offset(ix,y,iz),i%30==0&&w==0?light:floor);
            }
        }
        // Four supports and stairs keep each elevated ring reachable.
        for(net.minecraft.core.Direction d:net.minecraft.core.Direction.Plane.HORIZONTAL) {
            for(int h=0;h<y;h++) set(level,center.relative(d,radius).above(h),ModBlocks.CITADEL_ALLOY.get().defaultBlockState());
        }
    }

    private static void ring(ServerLevel level, BlockPos center, int radius, BlockState state) {
        for(int i=0;i<360;i+=4) {
            double a=Math.toRadians(i);
            set(level,center.offset((int)Math.round(Math.cos(a)*radius),0,(int)Math.round(Math.sin(a)*radius)),state);
        }
    }

    private static void spawnCitizens(ServerLevel level) {
        String[] ricks={"Rick D-151","Rick B-921","Rick J-440","Rick K-083","Rick V-706","Rick A-113","Rick G-217","Rick H-604","Rick Z-119","Rick Q-772","Rick F-340"};
        String[] mortys={"Morty D-151","Morty B-921","Morty J-440","Morty K-083","Morty V-706"};
        int ri=0,mi=0;
        for(int i=0;i<16;i++) {
            CitadelNpcEntity npc=ModEntityTypes.CITADEL_CITIZEN.get().create(level);
            if(npc==null) continue;
            double angle=i*Math.PI*2/16.0;
            int radius=12+(i%4)*6;
            npc.moveTo(CENTER.getX()+Math.cos(angle)*radius+0.5,CENTER.getY()+2,
                    CENTER.getZ()+Math.sin(angle)*radius+0.5,(float)Math.toDegrees(angle),0);
            boolean morty=i%3==0;npc.setVariant(morty?CitadelNpcEntity.Variant.MORTY:CitadelNpcEntity.Variant.RICK);
            npc.setCustomName(net.minecraft.network.chat.Component.literal(morty?mortys[mi++%mortys.length]:ricks[ri++%ricks.length]));
            npc.setCustomNameVisible(true);
            npc.setPersistenceRequired();
            level.addFreshEntity(npc);
        }
    }

    private static void ensurePersonnel(ServerLevel level) {
        java.util.List<CitadelNpcEntity> all=level.getEntitiesOfClass(CitadelNpcEntity.class,new AABB(CENTER).inflate(92));
        String[] names={"Rick D-151","Rick B-921","Rick J-440","Rick K-083","Rick V-706","Rick A-113","Rick G-217","Rick H-604","Morty D-151","Morty B-921","Morty J-440","Morty K-083"};
        int named=0;for(CitadelNpcEntity npc:all)if(!npc.hasCustomName()&&(npc.getVariant()==CitadelNpcEntity.Variant.RICK||npc.getVariant()==CitadelNpcEntity.Variant.MORTY)){npc.setCustomName(net.minecraft.network.chat.Component.literal(names[named++%names.length]));npc.setCustomNameVisible(true);}
        // Remover guardas excedentes de saves antigos (limite máximo: 4)
        java.util.List<CitadelNpcEntity> guardList=new java.util.ArrayList<>();
        for(CitadelNpcEntity n:all){if(n.getVariant()==CitadelNpcEntity.Variant.GUARD)guardList.add(n);}
        for(int i=4;i<guardList.size();i++){guardList.get(i).discard();}
        long council=all.stream().filter(n->n.getVariant()==CitadelNpcEntity.Variant.COUNCIL).count();
        for(int i=(int)council;i<5;i++){
            double a=i*Math.PI*2/5.0;
            int sx=(int)Math.round(Math.cos(a)*6.0), sz=(int)Math.round(Math.sin(a)*6.0);
            spawnPersonnel(level,CitadelNpcEntity.Variant.COUNCIL,
                    CENTER.offset(sx,2,-31+sz),"Council Rick "+(i+1));
        }
        long guards=all.stream().filter(n->n.getVariant()==CitadelNpcEntity.Variant.GUARD).count();
        // Reduzido para 4 guardas (apenas entrada principal) para diminuir lag na Cidadela
        BlockPos[] posts={CENTER.offset(-7,2,8),CENTER.offset(7,2,8),CENTER.offset(-7,2,-8),CENTER.offset(7,2,-8)};
        for(int i=(int)guards;i<posts.length;i++){
            spawnPersonnel(level,CitadelNpcEntity.Variant.GUARD,posts[i],"Citadel Guard "+String.format("%02d",i+1));
        }
        // Assign patrol routes to ALL guards (existing + newly spawned) so they walk the perimeter
        for (CitadelNpcEntity guard : level.getEntitiesOfClass(CitadelNpcEntity.class,
                new AABB(CENTER).inflate(24), n -> n.getVariant() == CitadelNpcEntity.Variant.GUARD)) {
            guard.setPatrolRoute(posts);
        }
    }

    private static void spawnPersonnel(ServerLevel level,CitadelNpcEntity.Variant variant,BlockPos pos,String name) {
        CitadelNpcEntity npc=ModEntityTypes.CITADEL_CITIZEN.get().create(level);if(npc==null)return;
        npc.moveTo(pos.getX()+.5,pos.getY(),pos.getZ()+.5,0,0);npc.setVariant(variant);
        npc.setCustomName(net.minecraft.network.chat.Component.literal(name));npc.setCustomNameVisible(true);
        npc.setPersistenceRequired();level.addFreshEntity(npc);
    }

    private static void set(ServerLevel level, BlockPos pos, BlockState state) {
        level.setBlock(pos,state,2);
    }

    private CitadelBuilder() {}
}
